import { NextRequest, NextResponse } from "next/server";
import { sendMail, brandHeader, brandFooter, kvRow, TEAM_EMAILS } from "@/lib/mailer";

interface SendReportPayload {
  to: "edna" | "mary" | "team" | "custom";
  customEmails?: string[];
  reportTitle: string;
  reportPeriod: string;
  summary: string;
  kpis: Record<string, string | number>;
  highlights?: string[];
  // Optional PDF attachment as base64 (produced client-side by jsPDF)
  pdfBase64?: string;
  pdfFilename?: string;
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as SendReportPayload;

    let recipients: string[] = [];
    switch (body.to) {
      case "edna":
        recipients = TEAM_EMAILS.edna ? [TEAM_EMAILS.edna] : [];
        break;
      case "mary":
        recipients = TEAM_EMAILS.mary ? [TEAM_EMAILS.mary] : [];
        break;
      case "team":
        recipients = TEAM_EMAILS.all;
        break;
      case "custom":
        recipients = (body.customEmails ?? []).filter(Boolean);
        break;
    }

    if (recipients.length === 0) {
      return NextResponse.json(
        { error: "No recipients resolved for the selected group" },
        { status: 400 }
      );
    }

    const kpiRows = Object.entries(body.kpis)
      .map(([k, v]) => kvRow(k, String(v)))
      .join("");

    const highlightList = body.highlights?.length
      ? `
        <div style="margin-top: 16px;">
          <p style="color: #071637; font-weight: 600; margin: 0 0 8px;">Key highlights</p>
          <ul style="margin: 0; padding-left: 20px; color: #141413; line-height: 1.6;">
            ${body.highlights.map((h) => `<li style="margin-bottom: 4px;">${h}</li>`).join("")}
          </ul>
        </div>
      `
      : "";

    const html = `
      <div style="font-family: Inter, Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        ${brandHeader(body.reportTitle, body.reportPeriod)}
        <div style="border: 1px solid #DDDDDD; border-top: none; padding: 24px;">
          <p style="color: #141413; margin: 0 0 16px; line-height: 1.55;">${body.summary}</p>
          <table style="width: 100%; border-collapse: collapse;">${kpiRows}</table>
          ${highlightList}
          ${
            body.pdfBase64
              ? '<p style="margin-top: 20px; color: #6B6B68; font-size: 12px;">📎 Full PDF report is attached.</p>'
              : ""
          }
          <hr style="margin: 20px 0; border: none; border-top: 1px solid #DDDDDD;" />
          <p style="color: #6B6B68; font-size: 12px; margin: 0;">
            Generated by Six Rivers Community Intelligence Platform · Six Rivers Africa
          </p>
        </div>
        ${brandFooter()}
      </div>
    `;

    // Build attachment from base64 if provided
    const attachments = body.pdfBase64
      ? [
          {
            filename: body.pdfFilename ?? "Six_Rivers_Report.pdf",
            content: Buffer.from(body.pdfBase64, "base64"),
            contentType: "application/pdf",
          },
        ]
      : undefined;

    const result = await sendMail({
      to: recipients,
      subject: `${body.reportTitle} · ${body.reportPeriod}`,
      html,
      attachments,
    });

    if (!result.sent) {
      return NextResponse.json({ error: result.error ?? "Mail send failed" }, { status: 500 });
    }

    return NextResponse.json({ success: true, recipients: result.recipients });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
